"""Tests for PR creation via gh CLI. Mocks subprocess.run."""

from pathlib import Path
from unittest.mock import MagicMock, patch

from action_harness.models import EvalResult, PrResult
from action_harness.pr import _build_pr_body, create_pr


def _success_eval() -> EvalResult:
    return EvalResult(
        success=True,
        stage="eval",
        commands_run=4,
        commands_passed=4,
    )


def _failed_eval() -> EvalResult:
    return EvalResult(
        success=False,
        stage="eval",
        error="Eval failed: uv run pytest -v",
        commands_run=2,
        commands_passed=1,
        failed_command="uv run pytest -v",
    )


class TestBuildPrBody:
    def test_includes_change_name(self) -> None:
        body = _build_pr_body("add-logging", _success_eval())
        assert "add-logging" in body

    def test_includes_eval_summary_success(self) -> None:
        body = _build_pr_body("test", _success_eval())
        assert "4/4 eval commands passed" in body

    def test_includes_eval_summary_failure(self) -> None:
        body = _build_pr_body("test", _failed_eval())
        assert "1/2 eval commands passed" in body
        assert "uv run pytest -v" in body

    def test_includes_footer(self) -> None:
        body = _build_pr_body("test", _success_eval())
        assert "Generated by action-harness" in body

    def test_failed_command_none_shows_unknown(self) -> None:
        eval_result = EvalResult(
            success=False,
            stage="eval",
            commands_run=2,
            commands_passed=1,
        )
        body = _build_pr_body("test", eval_result)
        assert "unknown" in body
        assert "None" not in body


class TestCreatePr:
    def _mock_subprocess(
        self,
        push_rc: int = 0,
        push_stderr: str = "",
        gh_rc: int = 0,
        gh_stdout: str = "https://github.com/org/repo/pull/42",
        gh_stderr: str = "",
    ) -> MagicMock:
        mock = MagicMock()

        def side_effect(cmd: list[str], **kwargs: object) -> MagicMock:
            result = MagicMock()
            if cmd[0] == "git" and "push" in cmd:
                result.returncode = push_rc
                result.stdout = ""
                result.stderr = push_stderr
            elif cmd[0] == "gh":
                result.returncode = gh_rc
                result.stdout = gh_stdout
                result.stderr = gh_stderr
            else:
                result.returncode = 0
                result.stdout = ""
                result.stderr = ""
            return result

        mock.side_effect = side_effect
        return mock

    def test_successful_pr(self) -> None:
        mock = self._mock_subprocess()

        with patch("action_harness.pr.subprocess.run", mock):
            result = create_pr(
                "test-change",
                Path("/wt"),
                "harness/test-change",
                _success_eval(),
            )

        assert result.success is True
        assert result.pr_url == "https://github.com/org/repo/pull/42"
        assert result.branch == "harness/test-change"
        assert result.error is None
        assert isinstance(result, PrResult)

    def test_push_failure_returns_early(self) -> None:
        mock = self._mock_subprocess(push_rc=1, push_stderr="permission denied")

        with patch("action_harness.pr.subprocess.run", mock):
            result = create_pr(
                "test-change",
                Path("/wt"),
                "harness/test-change",
                _success_eval(),
            )

        assert result.success is False
        assert "push failed" in (result.error or "")
        # Should only call git push, never gh pr create
        assert mock.call_count == 1

    def test_gh_create_failure(self) -> None:
        mock = self._mock_subprocess(gh_rc=1, gh_stderr="not authenticated")

        with patch("action_harness.pr.subprocess.run", mock):
            result = create_pr(
                "test-change",
                Path("/wt"),
                "harness/test-change",
                _success_eval(),
            )

        assert result.success is False
        assert "gh pr create failed" in (result.error or "")

    def test_push_command_construction(self) -> None:
        mock = self._mock_subprocess()

        with patch("action_harness.pr.subprocess.run", mock):
            create_pr(
                "test-change",
                Path("/wt"),
                "harness/test-change",
                _success_eval(),
            )

        push_call = mock.call_args_list[0]
        cmd = push_call[0][0]
        assert cmd == ["git", "push", "-u", "origin", "harness/test-change"]
        assert push_call[1]["cwd"] == Path("/wt")

    def test_gh_command_includes_title_and_body(self) -> None:
        mock = self._mock_subprocess()

        with patch("action_harness.pr.subprocess.run", mock):
            create_pr(
                "my-feature",
                Path("/wt"),
                "harness/my-feature",
                _success_eval(),
            )

        gh_call = mock.call_args_list[1]
        cmd = gh_call[0][0]
        assert "--title" in cmd
        title_idx = cmd.index("--title")
        assert cmd[title_idx + 1] == "[harness] my-feature"
        assert "--body" in cmd
        assert "--head" in cmd
        head_idx = cmd.index("--head")
        assert cmd[head_idx + 1] == "harness/my-feature"

    def test_pr_url_returned(self) -> None:
        mock = self._mock_subprocess(gh_stdout="https://github.com/o/r/pull/99\n")

        with patch("action_harness.pr.subprocess.run", mock):
            result = create_pr(
                "test",
                Path("/wt"),
                "harness/test",
                _success_eval(),
            )

        assert result.pr_url == "https://github.com/o/r/pull/99"
