"""Tests for PR creation via gh CLI. Mocks subprocess.run."""

from pathlib import Path
from unittest.mock import MagicMock, patch

from action_harness.models import EvalResult, PrResult, WorkerResult
from action_harness.pr import _build_pr_body, _read_proposal_why, create_pr


def _success_eval() -> EvalResult:
    return EvalResult(
        success=True,
        stage="eval",
        commands_run=4,
        commands_passed=4,
    )


def _failed_eval() -> EvalResult:
    return EvalResult(
        success=False,
        stage="eval",
        error="Eval failed: uv run pytest -v",
        commands_run=2,
        commands_passed=1,
        failed_command="uv run pytest -v",
    )


def _sample_worker() -> WorkerResult:
    return WorkerResult(
        success=True,
        stage="worker",
        cost_usd=0.42,
        duration_seconds=120.0,
        worker_output="All tests pass, feature implemented.",
    )


class TestReadProposalWhy:
    def test_extracts_why_section(self, tmp_path: Path) -> None:
        change_dir = tmp_path / "openspec" / "changes" / "my-change"
        change_dir.mkdir(parents=True)
        (change_dir / "proposal.md").write_text(
            "## Why\n\nThis is important.\n\n## What Changes\n\nStuff.\n"
        )
        result = _read_proposal_why(tmp_path, "my-change")
        assert result == "This is important."

    def test_why_at_end_of_file(self, tmp_path: Path) -> None:
        change_dir = tmp_path / "openspec" / "changes" / "my-change"
        change_dir.mkdir(parents=True)
        (change_dir / "proposal.md").write_text("## Why\n\nLast section content.\n")
        result = _read_proposal_why(tmp_path, "my-change")
        assert result == "Last section content."

    def test_file_missing_returns_none(self, tmp_path: Path) -> None:
        result = _read_proposal_why(tmp_path, "no-such-change")
        assert result is None

    def test_no_why_section_returns_none(self, tmp_path: Path) -> None:
        change_dir = tmp_path / "openspec" / "changes" / "my-change"
        change_dir.mkdir(parents=True)
        (change_dir / "proposal.md").write_text("## What Changes\n\nStuff.\n")
        result = _read_proposal_why(tmp_path, "my-change")
        assert result is None


class TestBuildPrBody:
    """Test _build_pr_body with enriched sections."""

    def _mock_git_calls(
        self,
        diff_stat: str | None = "file.py | 10 ++++\n 1 file changed",
        commit_log: str | None = "abc1234 Add feature",
    ) -> MagicMock:
        mock = MagicMock()

        def side_effect(cmd: list[str], **kwargs: object) -> MagicMock:
            result = MagicMock()
            if "diff" in cmd and "--stat" in cmd:
                if diff_stat is None:
                    result.returncode = 1
                    result.stdout = ""
                else:
                    result.returncode = 0
                    result.stdout = diff_stat
            elif "log" in cmd and "--oneline" in cmd:
                if commit_log is None:
                    result.returncode = 1
                    result.stdout = ""
                else:
                    result.returncode = 0
                    result.stdout = commit_log
            else:
                result.returncode = 0
                result.stdout = ""
            result.stderr = ""
            return result

        mock.side_effect = side_effect
        return mock

    def test_includes_change_name(self, tmp_path: Path) -> None:
        mock = self._mock_git_calls()
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("add-logging", _success_eval(), tmp_path, "main")
        assert "add-logging" in body

    def test_includes_eval_summary_success(self, tmp_path: Path) -> None:
        mock = self._mock_git_calls()
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", _success_eval(), tmp_path, "main")
        assert "4/4 eval commands passed" in body

    def test_includes_eval_summary_failure(self, tmp_path: Path) -> None:
        mock = self._mock_git_calls()
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", _failed_eval(), tmp_path, "main")
        assert "1/2 eval commands passed" in body
        assert "uv run pytest -v" in body

    def test_includes_footer(self, tmp_path: Path) -> None:
        mock = self._mock_git_calls()
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", _success_eval(), tmp_path, "main")
        assert "Generated by action-harness" in body

    def test_failed_command_none_shows_unknown(self, tmp_path: Path) -> None:
        eval_result = EvalResult(
            success=False,
            stage="eval",
            commands_run=2,
            commands_passed=1,
        )
        mock = self._mock_git_calls()
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", eval_result, tmp_path, "main")
        assert "unknown" in body
        assert "None" not in body

    def test_background_section_from_proposal(self, tmp_path: Path) -> None:
        change_dir = tmp_path / "openspec" / "changes" / "my-change"
        change_dir.mkdir(parents=True)
        (change_dir / "proposal.md").write_text("## Why\n\nBecause reasons.\n\n## What\n\nX.\n")
        mock = self._mock_git_calls()
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("my-change", _success_eval(), tmp_path, "main")
        assert "### Background" in body
        assert "Because reasons." in body

    def test_no_background_when_no_proposal(self, tmp_path: Path) -> None:
        mock = self._mock_git_calls()
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("my-change", _success_eval(), tmp_path, "main")
        assert "### Background" not in body

    def test_changes_section_with_diff_stat(self, tmp_path: Path) -> None:
        mock = self._mock_git_calls(diff_stat="pr.py | 5 +++++\n 1 file changed")
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", _success_eval(), tmp_path, "main")
        assert "### Changes" in body
        assert "pr.py | 5 +++++" in body

    def test_commits_section_with_log(self, tmp_path: Path) -> None:
        mock = self._mock_git_calls(commit_log="abc1234 First\ndef5678 Second")
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", _success_eval(), tmp_path, "main")
        assert "### Commits" in body
        assert "abc1234 First" in body

    def test_diff_stat_truncation(self, tmp_path: Path) -> None:
        long_stat = "\n".join(f"file{i}.py | 1 +" for i in range(35))
        mock = self._mock_git_calls(diff_stat=long_stat)
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", _success_eval(), tmp_path, "main")
        assert "... (truncated)" in body
        # Should have only 30 lines of stat, not 35
        assert "file30.py" not in body
        assert "file29.py" in body

    def test_worker_section_with_cost_duration_observations(self, tmp_path: Path) -> None:
        mock = self._mock_git_calls()
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body(
                "test", _success_eval(), tmp_path, "main", worker_result=_sample_worker()
            )
        assert "### Worker" in body
        assert "$0.42" in body
        assert "120s" in body
        assert "All tests pass" in body

    def test_worker_observations_truncation(self, tmp_path: Path) -> None:
        worker = WorkerResult(
            success=True,
            stage="worker",
            worker_output="A" * 600,
        )
        mock = self._mock_git_calls()
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", _success_eval(), tmp_path, "main", worker_result=worker)
        assert "... (truncated)" in body
        # The observations should be 500 chars + "... (truncated)"
        assert "A" * 500 in body
        assert "A" * 501 not in body

    def test_worker_section_omits_missing_fields(self, tmp_path: Path) -> None:
        worker = WorkerResult(success=True, stage="worker")
        mock = self._mock_git_calls()
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", _success_eval(), tmp_path, "main", worker_result=worker)
        # No worker section if all fields are None
        assert "### Worker" not in body

    def test_no_worker_section_when_none(self, tmp_path: Path) -> None:
        mock = self._mock_git_calls()
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", _success_eval(), tmp_path, "main")
        assert "### Worker" not in body

    def test_omits_changes_when_git_fails(self, tmp_path: Path) -> None:
        mock = self._mock_git_calls(diff_stat=None)
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", _success_eval(), tmp_path, "main")
        assert "### Changes" not in body

    def test_omits_commits_when_git_fails(self, tmp_path: Path) -> None:
        mock = self._mock_git_calls(commit_log=None)
        with patch("action_harness.pr.subprocess.run", mock):
            body = _build_pr_body("test", _success_eval(), tmp_path, "main")
        assert "### Commits" not in body


class TestCreatePr:
    def _mock_subprocess(
        self,
        push_rc: int = 0,
        push_stderr: str = "",
        gh_rc: int = 0,
        gh_stdout: str = "https://github.com/org/repo/pull/42",
        gh_stderr: str = "",
    ) -> MagicMock:
        mock = MagicMock()

        def side_effect(cmd: list[str], **kwargs: object) -> MagicMock:
            result = MagicMock()
            if cmd[0] == "git" and "push" in cmd:
                result.returncode = push_rc
                result.stdout = ""
                result.stderr = push_stderr
            elif cmd[0] == "gh":
                result.returncode = gh_rc
                result.stdout = gh_stdout
                result.stderr = gh_stderr
            else:
                result.returncode = 0
                result.stdout = ""
                result.stderr = ""
            return result

        mock.side_effect = side_effect
        return mock

    def test_successful_pr(self) -> None:
        mock = self._mock_subprocess()

        with patch("action_harness.pr.subprocess.run", mock):
            result = create_pr(
                "test-change",
                Path("/wt"),
                "harness/test-change",
                _success_eval(),
                worker_result=_sample_worker(),
                base_branch="main",
            )

        assert result.success is True
        assert result.pr_url == "https://github.com/org/repo/pull/42"
        assert result.branch == "harness/test-change"
        assert result.error is None
        assert isinstance(result, PrResult)

    def test_push_failure_returns_early(self) -> None:
        mock = self._mock_subprocess(push_rc=1, push_stderr="permission denied")

        with patch("action_harness.pr.subprocess.run", mock):
            result = create_pr(
                "test-change",
                Path("/wt"),
                "harness/test-change",
                _success_eval(),
                worker_result=_sample_worker(),
                base_branch="main",
            )

        assert result.success is False
        assert "push failed" in (result.error or "")
        # Should only call git push, never gh pr create
        assert mock.call_count == 1

    def test_gh_create_failure(self) -> None:
        mock = self._mock_subprocess(gh_rc=1, gh_stderr="not authenticated")

        with patch("action_harness.pr.subprocess.run", mock):
            result = create_pr(
                "test-change",
                Path("/wt"),
                "harness/test-change",
                _success_eval(),
                worker_result=_sample_worker(),
                base_branch="main",
            )

        assert result.success is False
        assert "gh pr create failed" in (result.error or "")

    def test_push_command_construction(self) -> None:
        mock = self._mock_subprocess()

        with patch("action_harness.pr.subprocess.run", mock):
            create_pr(
                "test-change",
                Path("/wt"),
                "harness/test-change",
                _success_eval(),
                worker_result=_sample_worker(),
                base_branch="main",
            )

        push_call = mock.call_args_list[0]
        cmd = push_call[0][0]
        assert cmd == ["git", "push", "-u", "origin", "harness/test-change"]
        assert push_call[1]["cwd"] == Path("/wt")

    def test_gh_command_includes_title_and_body(self) -> None:
        mock = self._mock_subprocess()

        with patch("action_harness.pr.subprocess.run", mock):
            create_pr(
                "my-feature",
                Path("/wt"),
                "harness/my-feature",
                _success_eval(),
                worker_result=_sample_worker(),
                base_branch="main",
            )

        # Find the gh call (index varies due to git diff/log calls in _build_pr_body)
        gh_calls = [c for c in mock.call_args_list if c[0][0][0] == "gh"]
        assert len(gh_calls) == 1
        cmd = gh_calls[0][0][0]
        assert "--title" in cmd
        title_idx = cmd.index("--title")
        assert cmd[title_idx + 1] == "[harness] my-feature"
        assert "--body" in cmd
        assert "--head" in cmd
        head_idx = cmd.index("--head")
        assert cmd[head_idx + 1] == "harness/my-feature"

    def test_pr_url_returned(self) -> None:
        mock = self._mock_subprocess(gh_stdout="https://github.com/o/r/pull/99\n")

        with patch("action_harness.pr.subprocess.run", mock):
            result = create_pr(
                "test",
                Path("/wt"),
                "harness/test",
                _success_eval(),
                worker_result=_sample_worker(),
                base_branch="main",
            )

        assert result.pr_url == "https://github.com/o/r/pull/99"

    def test_backward_compatible_without_worker(self) -> None:
        """create_pr works without worker_result (defaults to None)."""
        mock = self._mock_subprocess()

        with patch("action_harness.pr.subprocess.run", mock):
            result = create_pr(
                "test-change",
                Path("/wt"),
                "harness/test-change",
                _success_eval(),
            )

        assert result.success is True
