"""PR creation via gh CLI."""

import subprocess
from pathlib import Path

import typer

from action_harness.models import EvalResult, PrResult


def create_pr(
    change_name: str,
    repo: Path,
    worktree_path: Path,
    branch: str,
    eval_result: EvalResult,
    verbose: bool = False,
) -> PrResult:
    """Push branch and open a PR via gh CLI.

    Pushes the worktree branch to origin, then creates a PR with a structured
    title and body. Returns the PR URL.

    Note: gh CLI availability is validated by cli.validate_inputs before
    the pipeline starts. This function assumes gh is in PATH.
    """
    typer.echo(f"[pr] pushing branch '{branch}'", err=True)

    # Push branch to remote
    push_result = subprocess.run(
        ["git", "push", "-u", "origin", branch],
        cwd=worktree_path,
        capture_output=True,
        text=True,
    )
    if push_result.returncode != 0:
        typer.echo(f"[pr] push failed: {push_result.stderr.strip()}", err=True)
        return PrResult(
            success=False,
            stage="pr",
            error=f"git push failed: {push_result.stderr.strip()}",
            branch=branch,
        )

    if verbose:
        typer.echo(f"  pushed to origin/{branch}", err=True)

    # Build PR body
    title = f"[harness] {change_name}"
    body = _build_pr_body(change_name, eval_result)

    if verbose:
        typer.echo(f"  title: {title}", err=True)

    # Create PR via gh CLI
    gh_result = subprocess.run(
        [
            "gh",
            "pr",
            "create",
            "--title",
            title,
            "--body",
            body,
            "--head",
            branch,
        ],
        cwd=worktree_path,
        capture_output=True,
        text=True,
    )

    if gh_result.returncode != 0:
        typer.echo(f"[pr] gh pr create failed: {gh_result.stderr.strip()}", err=True)
        return PrResult(
            success=False,
            stage="pr",
            error=f"gh pr create failed: {gh_result.stderr.strip()}",
            branch=branch,
        )

    pr_url = gh_result.stdout.strip()
    typer.echo(pr_url)  # Final output to stdout
    typer.echo(f"[pr] created: {pr_url}", err=True)

    return PrResult(
        success=True,
        stage="pr",
        pr_url=pr_url,
        branch=branch,
    )


def _build_pr_body(change_name: str, eval_result: EvalResult) -> str:
    """Build structured PR body."""
    eval_summary = (
        f"All {eval_result.commands_passed}/{eval_result.commands_run} eval commands passed"
        if eval_result.success
        else f"{eval_result.commands_passed}/{eval_result.commands_run} eval commands passed "
        f"(failed: {eval_result.failed_command})"
    )

    return (
        f"## Change: {change_name}\n\n"
        f"### Eval Results\n"
        f"{eval_summary}\n\n"
        f"---\n"
        f"Generated by action-harness"
    )
